@component('mail::message')
# Payment of {{ $paymenttype }} for {{ $reservation->eventtitle }}

Dear Mr./Ms./Mrs. {{ $customer->name }},

You only have {{ $days }} days to pay for the {{ $paymenttype }} of your reservation.

Thanks,<br>
{{ config('app.name') }}
<br><br>
This email is auto-generated by the system. Please do not reply to this email.
@endcomponent
